let details = [
  {
      'name': 'Abhimanyu Tyagi',
      'designation': 'Member',
      'src': './components/images/members/img1.jpeg',
      'email':'manyu.tyagisep21@gmail.com',
      'intro':'Abhimanyu Tyagi is a visionary graphic designer known for his innovative use of color and striking visual compositions.',
      'skills':['Canva', 'Adobe Illustrator', 'Figma'],
      'work': ['./components/images/allWork/ABHIMANYU TIYAGI.png']
  },
  {
      'name': 'Abhishek Tiwari',
      'designation': 'Member',
      'src': './components/images/members/img2.jpg',
      'email':'manyu.jaykanttiwari1212@gmail.com',
      'intro':'I am a passionate designer who likes to design different posters which can convey something ',
      'skills':['Canva', 'Adobe photoshop'],
      'work': ['./components/images/allWork/ABHISHEK TIWARI.png']
  },
  {
      'name': 'Akshat',
      'designation': 'Member',
      'src': './components/images/members/img3.jpg',
      'email':'manyu.akshatsharma200705@gmail.com',
      'intro':'Hi everyone,My name is AkshatSharma, and I’m thrilled to be here at Trinity Institute Of Profession Studies. and I’m really passionate about designing.In my free time, I enjoy to play games, doing designing and reading books, and I got privileged to join Apex Club [Designing Society Of TIPS] I’m always excited to meet new people, learn new things.Looking forward to a great year together!',
      'skills':['Canva', 'Adobe photoshop', 'Figma'],
  },
  {
      'name': 'Alok',
      'designation': 'Member',
      'src': './components/images/members/img4.jpg',
      'email':'alokupadhayay08@gmail.com',
      'intro':"Hello I'm Alok Kumar Upadhayay and currently I'm pursuing graduation in Bachelor's in Computer Applications programme.",
      'skills':['Knowledge of video editing', 'knowledge of poster designing'],
  },
  {
      'name': 'Anchal',
      'designation': 'Member',
      'src': './components/images/members/img5.jpg',
      'email':'anchallingwal05@gmail.com',
      'intro':"My name is anchal lingwal.I'm doing bca. I am a member of apex societyI'm good at digital drawing, canva and i know basic editing. I know software like canva, ibix paint, capcut, figma.",
      'skills':['drawing', 'time management'],
  },
  {
      'name': 'Ansh',
      'designation': 'Member',
      'src': './components/images/members/img6.jpg',
      'email':'sahansh2004@gmail.com',
      'intro':"Hello! I'm Ansh a passionate and creative graphic designer. My expertise spans a wide range of design disciplines, including branding, digital and print media, and visual storytelling. With a keen eye for detail and a commitment to delivering high-quality work, I strive to create designs that not only meet client expectations but also exceed them.",
      'skills':['Adobe Photoshop', 'Adobe Illustrator', 'Adobe InDesign'],
  },
  {
      'name': 'Arv Oberoi',
      'designation': 'Member',
      'src': './components/images/members/img7.jpg',
      'email':'arvoberoi21@gmail.com',
      'intro':'Currently Completing my BCA from Trinity Institute of Professional Studies. Have interst in Designing. Want to Learn more from APEX Mentors. ',
      'skills':['Worked on FIGMA ', 'adobe photoshop'],
  },
  {
      'name': 'Deepesh Negi',
      'designation': 'Member',
      'src': './components/images/members/img8.png',
      'email':'negi.dragonmaster@gmail.com',
      'intro':'My self deepesh Negi, BAJMC 1ST year, I am Cool, calm, chill, always ready to learn something new, always try to do my best in all the task assigned to me. Open minded, available to help PPL',
      'skills':['Photoshop', 'Microsoft', 'photography','creative mind','good analysing skil','good at SEO'],
  },
  {

      'name': 'Divay Chillar',
      'designation': 'Member',
      'src': './components/images/members/img9.jpg',
      'email':'divaychhillar@gmail.com',
      'intro':"Hi there! I’m Divay Chhillar, a curious soul with a passion for both technology and creativity. By day, I dive into the world of programming languages, databases, and AI design. If you’re ever in need of a blend of technical expertise and imaginative flair, you’ve found the right person!",
      'skills':['UI/UX'],
  },
  {
      'name': 'Krish Arora',
      'designation': 'Member',
      'src': './components/images/members/img10.jpg',
      'email':'krish9278965065@gmail.com',
      'intro':"I'm a graphic design student. I'm learning and using programs like Photoshop and Illustrator. Eager to contribute creative solutions and a passion for visual communication to a design team.",
      'skills':['Canva', 'Illustrator', 'photoshop'],
  },
  {
      'name': 'Kritika',
      'designation': 'Member',
      'src': './components/images/members/img11.jpg',
      'email':'kritikachandhok92@gmail.com',
      'intro':"I'm a computer science student at Trinity Institute of Innovation in Professional Studies. Driven by a passion for technology, I'm actively developing my skills in web development (HTML, CSS, JavaScript, MySQL), data structures & algorithms, and Python. I'm a quick learner and possess a strong determination to tackle any technical challenge.",
      'skills':['Canva', 'python', 'Figma',' UI UX'],
  },
  {
      'name': 'Kushagra Rastogi',
      'designation': 'Member',
      'src': './components/images/members/img12.jpg',
      'email':'kushagrarastogi783@gmail.com',
      'intro':'Hello myself Kushagra Rastogi currently pursuing BCA. I like to show my creativity in 3d arts.',
      'skills':['3d modelling'],
  },
  {
      'name': 'Mahak Preet Kaur',
      'designation': 'Member',
      'src': './components/images/members/img13.jpg',
      'email':'mahakpreet65@gmail.com',
      'intro':"Hey Apexians! My name is Mahak Preet Kaur, and I am a member of the Apex Designing Society. As an enthusiastic Graphic Artist and Video Editor, I bring creativity and technical skills to my projects. With experience in Photoshop, Canva, and After Effects, I am passionate about transforming concepts into captivating visual stories.I recently acted as the creative lead in our fest, where I enjoyed experimenting with various design techniques. Eager to learn and grow, I look forward to contributing my skills to exciting projects and collaborating with talented professionals.",
      'skills':['Canva', 'Adobe Photoshop', 'Adobe After Effects'],
  },
  {
      'name': 'Mahi',
      'designation': 'Member',
      'src': './components/images/members/img14.jpg',
      'email':'mahisehra.98@gmail.com',
      'intro':"Hey Everyone, I am Mahi, currently in my second year of pursuing a BCA degree. My deep interest in design fuels my passion for the field. I am convinced that design is not solely about visual appeal but also about creating practical and impactful user experiences.",
      'skills':['Illustrator', 'Adobe photoshop', 'Figma'],
  },
  {
      'name': 'Megha Bhagat',
      'designation': 'Member',
      'src': './components/images/members/img15.png',
      'email':'megha.bhagat2212@gmail.com',
      'intro':"Hi, I'm 𝐌𝐞𝐠𝐡𝐚 𝐁𝐡𝐚𝐠𝐚𝐭, a proud member of the APEX Designing Society. Specializing in the graphic and AI departments, I excel in Canva and am currently expanding my skills in Photoshop and Illustrator. With a strong foundation in generative AI, I am passionate about blending AI with my designs to create innovative artworks. Always eager to learn and gain new experiences in designing, I am enthusiastic about turning ideas into creative masterpieces. Let's connect and explore the world of design together!",
      'skills':['Canva'],
  },
  {
      'name': 'Nancy Kashyap',
      'designation': 'Member',
      'src': './components/images/members/img16.jpg',
      'email':'nancykashyap3815@gmail.com',
      'intro':"Hello I'm Nancy and I'm in 1st year 2sem bca I'm the one who was incredibly excited about the apex auditions and to get selected but didn't quite hit the mark in my performances till date.Despite not achieving what I aimed for, these moments have been crucial in my learning journey and I've learnt a lot of things from here and will do so.",
      'skills':['Video editing', 'Adobe photoshop', 'canva '],
  },
  {
      'name': 'Paramjeet Singh',
      'designation': 'Member',
      'src': './components/images/members/img17.jpg',
      'email':'xxparamjitsinghxx@gmail.com',
      'intro':"Hello, I'm Paramjeet Singh, currently pursuing a Bachelor of Computer Applications (BCA) from Trinity Institute of Professional Studies (TIPS) in Dwarka. Alongside my academic pursuits, I am actively enhancing my creative skills by learning graphic designing through Apex, the designing society at TIPS. I have a foundational knowledge of design tools, including Canva and Figma, which I use to bring my creative ideas to life.",
      'skills':['Canva','Figma'],
  },
  {
      'name': 'Pragati Pant',
      'designation': 'Member',
      'src': './components/images/members/img18.jpg',
      'email':'ppant2005@gmail.com',
      'intro':"I am pragati pant.I have a passion of video and motion edits. I mostly edit on anime and i try to be better at it everyday.",
      'skills':['𝐂𝐚𝐧𝐯𝐚 𝐏𝐫𝐨𝐟𝐢𝐜𝐢𝐞𝐧𝐜𝐲', 'Adobe 𝐏𝐡𝐨𝐭𝐨𝐬𝐡𝐨𝐩'],
  },
  {
      'name': 'Pranav',
      'designation': 'Member',
      'src': './components/images/members/img19.jpg',
     'email':'pranav123rai@gmail.com',
      'intro':"Myself Pranav Rai , I am student of BCA 3rd Semester. I am enthusiasm towards designing and new things.",
      'skills':['Canva','Figma'],
      
  },
  {
      'name': 'Prashant',
      'designation': 'Member',
      'src': './components/images/members/img20.jpg',
      'email':'pk3065949@gmail.com',
      'intro':"My name is Prashant, I'm an enthusiastic graphic designer, Designing isn't just a skill for me – it's a part of my daily life. I often find myself immersed in design projects during my free time, experimenting with different concepts, and learning from each experience.",
      'skills':['Graphic Designing'],
  },
  {
      'name': 'Pulkit Darp',
      'designation': 'Member',
      'src': './components/images/members/img21.jpg',
      'email':'pulkitdarp@gmail.com',
      'intro':"I am Pulkit Darp, I love Designing and editing.",
      'skills':['Canva', 'Ai Image generation', 'Figma','Photoshop'],
  },
  {
      'name': 'Rishabh',
      'designation': 'Member',
      'src': './components/images/members/img22.jpg',
      'email':'yadavrishabh833@gmail.com',
      'intro':"Hello, I'm Rishabh I am currently a 2nd year student at Trinity institute of professional studies , majoring in BCA. My studies have given me a solid foundation in DBMS . Outside of academics, I enjoy traveling, listings musics which helps me stay balanced and motivated. I am passionate about Designing and video editing , and I am always eager to learn and grow in this area.",
      'skills':['Canva', 'Capcut', 'Figma'],
  },
  {
      'name': 'Rohan Singh Negi',
      'designation': 'Member',
      'src': './components/images/members/img23.png',
      'email':'rohannegi689@gmail.com',
      'intro':"I am student of BCA final year and the member of apex design society of our collage , i have knowledge about graphic designing and web designing.",
      'skills':['Web Development.', 'Graphic Designing'],
  },
  {
      'name': 'Rujul Varshney',
      'designation': 'Member',
      'src': './components/images/members/img24.jpg',
      'email':'rujul1005@gmail.com',
      'intro':"Hi, my name is RUJUL VARSHNEY, and I’m from New Delhi. I’m currently pursuing Bachelor's of computer application from Trinity institute of professional studies. I have a strong passion for coding & designing, am also a part of APEX designing society & ALFA coding club.",
      'skills':['Canva'],
  },
  {
    //no information
      'name': 'Sachin Choudhary',
      'designation': 'Member',
      'src': './components/images/members/img25.jpg',
      'email':'manyu.tyagisep21@gmail.com',
      'intro':'Abhimanyu Tyagi is a visionary graphic designer known for his innovative use of color and striking visual compositions.',
      'skills':['Canva', 'Adobe Illustrator', 'Figma'],
  },
  {
    //no information
      'name': 'Sameer Kapoor',
      'designation': 'Member',
      'src': './components/images/members/img26.jpg',
      'email':'manyu.tyagisep21@gmail.com',
      'intro':'Abhimanyu Tyagi is a visionary graphic designer known for his innovative use of color and striking visual compositions.',
      'skills':['Canva', 'Adobe Illustrator', 'Figma'],
  },
  {
      'name': 'Samriddhi',
      'designation': 'Member',
      'src': './components/images/members/img27.jpeg',
      'email':'sambraddhiparihar123@gmail.com',
      'intro':"Hi! Sambraddhi here. Bajmc student with a design eye. Always creative and a team player!",
      'skills':['Video editing', 'Adobe Illustrator'],
  },
  {
      'name': 'Shivam',
      'designation': 'Member',
      'src': './components/images/members/img28.jpg',
      'email':'1120shivamkumar@gmail.com',
      'intro':"Hello, I'm Shivam, a 3rd-year BCA student at IP University Delhi. I have keen interest in IT and additionally I am passionate about designing and I'm a member of APEX the graphic design society",
      'skills':['Canva', 'Adobe Illustrator', 'photoshop', 'filmora', 'premiere pro'],
  },
  {
      'name': 'Vishal Singh',
      'designation': 'Member',
      'src': './components/images/members/img29.jpg',
      'email':'ogresingh010304@gmail.com',
      'intro':"Hi! I'm Vishal Singh, currently pursuing a BCA and an enthusiastic member of Apex, the designing society of TIPS Dwarka. I love diving into all things creative, I'm always up for learning new tricks and finding cool ways to mix my skills. Whether it's through fun designs, awesome 3D models, or engaging video content.",
      'skills':['blender', 'Adobe photoshop', 'Figma', 'canva'],
  },
  {
      'name': 'Yug Dahiya',
      'designation': 'Member',
      'src': './components/images/members/img30.png',
      'email':'yugdahiya000@gmail.com',
      'intro':"Hello, I’m Yug Dahiya, a student at Trinity Institute  Professional Studies. I’m passionate about learning and contributing to our community. As I navigate this educational cosmos, I eagerly anticipate the discoveries that lie ahead",
      'skills':['Canva', 'Adobe Photoshop', 'Figma', 'Blender', 'Adobe illustrator'],
  }
];